name: Build Docker on Remote Machine

on:
  push:
    branches:
      - dev  # Adjust branch as needed
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: self-hosted  # Runs on your remote machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm cache
        uses: actions/cache@v3
        with:
          path: ~/.pnpm-store  # Path to pnpm cache directory
          key: pnpm-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-${{ runner.os }}-
      
      - name: Build Docker Image
        run: make nocache
