name: Build Docker on Remote Machine

on:
  push:
    branches:
      - dev  # Adjust branch as needed
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: self-hosted  # Runs on your remote machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup pnpm cache
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'
      
      - name: Build Docker Image
        run: make nocache
