name: Build Docker on Remote Machine

on:
  push:
    branches:
      - dev  # Adjust branch as needed

jobs:
  build:
    runs-on: self-hosted  # Runs on your remote machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: docker build -t oneblock-landing-landing-cms:latest .

      - name: Run Docker Container
        run: docker run -d --name oneblock_landing_cms oneblock-landing-landing-cms:latest
