name: Build on Oneblock VM

on:
  push:
    branches:
      - dev  # Adjust branch as needed
  workflow_dispatch:  # Enables manual trigger

jobs:
  build:
    runs-on: [self-hosted,ubuntu-latest]  # Runs on your remote machine
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Build Docker Image
        run: make nocache
